export const ACCOUNTING_COMMANDS = [
  {
    id: "acc_create_payment_voucher",
    title: "Create Payment Voucher",
    path: "/accounting/client/paymentVoucher",
    category: "Vouchers",
    defaultKeywords: [
      "payment",
      "pay",
      "voucher",
      "add payment",
      "new payment",
    ],
    icon: "CreditCard",
    shortcut: "adpv",
  },
  {
    id: "acc_create_receive_voucher",
    title: "Create Receipt Voucher",
    path: "/accounting/client/receptVoucher",
    category: "Vouchers",
    defaultKeywords: [
      "receive",
      "receipt",
      "voucher",
      "add receipt",
      "new receipt",
      "inward",
    ],
    icon: "ArrowDownLeft",
    shortcut: "adrv",
  },
  {
    id: "acc_create_purchase_voucher",
    title: "Create Purchase Voucher",
    path: "/accounting/client/purchasevoucher",
    category: "Vouchers",
    defaultKeywords: [
      "purchase",
      "buy",
      "voucher",
      "add purchase",
      "new purchase",
    ],
    icon: "ShoppingCart",
    shortcut: "adpur",
  },
  {
    id: "acc_create_sale_voucher",
    title: "Create Sale Voucher",
    path: "/accounting/client/salevoucher",
    category: "Vouchers",
    defaultKeywords: [
      "sale",
      "sell",
      "voucher",
      "add sale",
      "new sale",
      "invoice",
    ],
    icon: "Tag",
    shortcut: "adsale",
  },
  {
    id: "acc_create_journal_voucher",
    title: "Create Journal Voucher",
    path: "/accounting/client/journalvoucher",
    category: "Vouchers",
    defaultKeywords: ["journal", "jv", "voucher", "add journal", "adjustment"],
    icon: "BookOpen",
    shortcut: "adjv",
  },
  {
    id: "acc_create_contra_voucher",
    title: "Create Contra Voucher",
    path: "/accounting/client/contravoucher",
    category: "Vouchers",
    defaultKeywords: ["contra", "cash bank transfer", "voucher", "add contra"],
    icon: "Repeat",
    shortcut: "adcv",
  },
  {
    id: "acc_create_debit_note",
    title: "Create Debit Note",
    path: "/accounting/client/debitNote",
    category: "Vouchers",
    defaultKeywords: ["debit note", "dn", "purchase return", "add debit note"],
    icon: "FileMinus",
    shortcut: "addn",
  },
  {
    id: "acc_create_credit_note",
    title: "Create Credit Note",
    path: "/accounting/client/creditNote",
    category: "Vouchers",
    defaultKeywords: ["credit note", "cn", "sales return", "add credit note"],
    icon: "FilePlus",
    shortcut: "adcn",
  },

  {
    id: "acc_list_payment_vouchers",
    title: "Payment Vouchers List",
    path: "/accounting/client/listOfPaymentVoucher",
    category: "Registers",
    defaultKeywords: ["list payment", "payment list", "payment register"],
    icon: "ListFilter",
  },
  {
    id: "acc_list_receive_vouchers",
    title: "Receipt Vouchers List",
    path: "/accounting/client/listOfReciptVoucher",
    category: "Registers",
    defaultKeywords: ["list receipt", "receipt list", "receipt register"],
    icon: "ListFilter",
  },
  {
    id: "acc_list_purchase_vouchers",
    title: "Purchase Vouchers List",
    path: "/accounting/client/listOfPurchaseVoucher",
    category: "Registers",
    defaultKeywords: ["list purchase", "purchase list", "purchase register"],
    icon: "ListFilter",
  },
  {
    id: "acc_list_sale_vouchers",
    title: "Sale Vouchers List",
    path: "/accounting/client/listOfSaleVoucher",
    category: "Registers",
    defaultKeywords: ["list sale", "sale list", "sale register"],
    icon: "ListFilter",
  },
  {
    id: "acc_list_journal_vouchers",
    title: "Journal Vouchers List",
    path: "/accounting/client/listOfJournalVoucher",
    category: "Registers",
    defaultKeywords: ["list journal", "journal list", "journal register"],
    icon: "ListFilter",
  },
  {
    id: "acc_list_contra_vouchers",
    title: "Contra Vouchers List",
    path: "/accounting/client/listOfContraVoucher",
    category: "Registers",
    defaultKeywords: ["list contra", "contra list"],
    icon: "ListFilter",
  },
  {
    id: "acc_list_debit_notes",
    title: "Debit Notes List",
    path: "/accounting/client/debitNotesList",
    category: "Registers",
    defaultKeywords: ["list debit note", "debit note list"],
    icon: "ListFilter",
  },
  {
    id: "acc_list_credit_notes",
    title: "Credit Notes List",
    path: "/accounting/client/creditNotesList",
    category: "Registers",
    defaultKeywords: ["list credit note", "credit note list"],
    icon: "ListFilter",
  },

  {
    id: "acc_create_ledger",
    title: "Create New Ledger",
    path: "/accounting/client/ledger",
    category: "Masters",
    defaultKeywords: [
      "create ledger",
      "add ledger",
      "new account",
      "party ledger",
    ],
    icon: "UserPlus",
    shortcut: "adld",
  },
  {
    id: "acc_list_ledgers",
    title: "List of Ledgers",
    path: "/accounting/client/listOfLedgers",
    category: "Masters",
    defaultKeywords: ["ledger list", "all ledgers", "parties", "accounts"],
    icon: "Users",
  },
  {
    id: "acc_create_group",
    title: "Create Group",
    path: "/accounting/client/groupCreation",
    category: "Masters",
    defaultKeywords: ["create group", "add group", "group creation"],
    icon: "FolderPlus",
    shortcut: "adgp",
  },
  {
    id: "acc_list_groups",
    title: "List of Groups",
    path: "/accounting/client/listOfGroups",
    category: "Masters",
    defaultKeywords: ["group list", "all groups", "chart of accounts"],
    icon: "FolderTree",
  },

  {
    id: "acc_day_book",
    title: "Day Book",
    path: "/accounting/client/dayBook",
    category: "Reports",
    defaultKeywords: ["daybook", "daily transactions", "today transactions"],
    icon: "Calendar",
    shortcut: "dybk",
  },
  {
    id: "acc_trial_balance",
    title: "Trial Balance",
    path: "/accounting/client/trialBalance",
    category: "Reports",
    defaultKeywords: ["tb", "trial balance", "balances", "financial statement"],
    icon: "Scale",
    shortcut: "trbl",
  },
  {
    id: "acc_gst_summary",
    title: "GST Summary",
    path: "/accounting/client/gst-summary",
    category: "Reports",
    defaultKeywords: ["gst", "tax", "gstr", "gst report"],
    icon: "Receipt",
  },
  {
    id: "acc_reports",
    title: "Financial Reports",
    path: "/accounting/client/reports",
    category: "Reports",
    defaultKeywords: ["reports", "financials", "balance sheet", "p&l"],
    icon: "BarChart3",
  },
  {
    id: "acc_statutory_reports",
    title: "Statutory Reports",
    path: "/accounting/client/statutoryReports",
    category: "Reports",
    defaultKeywords: ["statutory", "audit", "compliance"],
    icon: "FileCheck",
  },
  {
    id: "acc_bank_activities",
    title: "Bank Activities",
    path: "/accounting/client/bank-activities",
    category: "Banking",
    defaultKeywords: ["bank", "banking", "reconciliation", "statement"],
    icon: "Building2",
  },
  {
    id: "acc_cash_activities",
    title: "Cash Activities",
    path: "/accounting/client/cash",
    category: "Banking",
    defaultKeywords: ["cash", "petty cash", "cash register"],
    icon: "Banknote",
  },
  {
    id: "acc_dashboard",
    title: "Accounting Dashboard",
    path: "/accounting/client/dashboard",
    category: "Overview",
    defaultKeywords: ["accounting home", "dashboard", "overview"],
    icon: "LayoutDashboard",
  },
];

export const ALL_COMMANDS = [...ACCOUNTING_COMMANDS];
