export const hrmsPermissions = [
  // 1. Global HRMS Access
  { module: 'HRMS', action: 'Base Layout Access', code: 'hrms', description: 'Base access to the HRMS folder in the sidebar' },
  { module: 'HRMS', action: 'Super Admin Access', code: 'hrms.*', description: 'Complete access to the entire HRMS module (Super Admin level)' },

  // 2. Employee Management
  { module: 'HRMS', action: 'Employee Layout Access', code: 'hrms.employee', description: 'Access to Employee Management sidebar/routes' },
  { module: 'HRMS', action: 'Full Employee Access', code: 'hrms.employee.*', description: 'Complete access to all Employee Management features' },
  { module: 'HRMS', action: 'Active Tab Access', code: 'hrms.employee.active', description: 'Access to Active Employees tab' },
  { module: 'HRMS', action: 'Full Active Tab Access', code: 'hrms.employee.active.*', description: 'Complete access to actions in Active Employees tab' },
  { module: 'HRMS', action: 'Create Employee', code: 'hrms.employee.active.create', description: 'Ability to add a new employee' },
  { module: 'HRMS', action: 'Edit Employee', code: 'hrms.employee.active.edit', description: 'Ability to edit an active employee' },
  { module: 'HRMS', action: 'Delete Employee', code: 'hrms.employee.active.delete', description: 'Ability to delete an active employee' },
  { module: 'HRMS', action: 'Inactive Tab Access', code: 'hrms.employee.inactive', description: 'Access to Inactive/Resigned Employees tab' },
  { module: 'HRMS', action: 'Full Inactive Tab Access', code: 'hrms.employee.inactive.*', description: 'Complete access to actions in Inactive Employees tab' },
  { module: 'HRMS', action: 'View Inactive Employee', code: 'hrms.employee.inactive.view', description: 'Ability to view inactive employee details' },

  // 3. Attendance
  { module: 'HRMS', action: 'Attendance Layout Access', code: 'hrms.attendance', description: 'Access to Attendance sidebar/routes' },
  { module: 'HRMS', action: 'Full Attendance Access', code: 'hrms.attendance.*', description: 'Complete access to all Attendance features' },
  { module: 'HRMS', action: 'Daily Punch Tab Access', code: 'hrms.attendance.daily_punch', description: 'Access to Daily Punch tab' },
  { module: 'HRMS', action: 'Full Daily Punch Access', code: 'hrms.attendance.daily_punch.*', description: 'Complete access to Daily Punch actions' },
  { module: 'HRMS', action: 'View Daily Punch', code: 'hrms.attendance.daily_punch.view', description: 'Ability to view daily punches' },
  { module: 'HRMS', action: 'Edit Daily Punch', code: 'hrms.attendance.daily_punch.edit', description: 'Ability to manually modify a punch' },
  { module: 'HRMS', action: 'Create Daily Punch', code: 'hrms.attendance.daily_punch.create', description: 'Ability to create a daily punch' },
  { module: 'HRMS', action: 'Mispunch Tab Access', code: 'hrms.attendance.mispunch', description: 'Access to Mispunch Requests tab' },
  { module: 'HRMS', action: 'Full Mispunch Access', code: 'hrms.attendance.mispunch.*', description: 'Complete access to Mispunch actions' },
  { module: 'HRMS', action: 'Approve Mispunch', code: 'hrms.attendance.mispunch.approve', description: 'Ability to approve a mispunch' },
  { module: 'HRMS', action: 'Reject Mispunch', code: 'hrms.attendance.mispunch.reject', description: 'Ability to reject a mispunch' },
  { module: 'HRMS', action: 'Leaves Tab Access', code: 'hrms.attendance.leaves', description: 'Access to Leave Requests tab' },
  { module: 'HRMS', action: 'Full Leaves Access', code: 'hrms.attendance.leaves.*', description: 'Complete access to Leave Request actions' },
  { module: 'HRMS', action: 'Approve Leave', code: 'hrms.attendance.leaves.approve', description: 'Ability to approve a leave request' },
  { module: 'HRMS', action: 'Reject Leave', code: 'hrms.attendance.leaves.reject', description: 'Ability to reject a leave request' },

  // 4. Task Management
  { module: 'HRMS', action: 'Tasks Layout Access', code: 'hrms.tasks', description: 'Access to Task Management sidebar/routes' },
  { module: 'HRMS', action: 'Full Tasks Access', code: 'hrms.tasks.*', description: 'Complete access to all Task features' },
  { module: 'HRMS', action: 'Assigned Tab Access', code: 'hrms.tasks.assigned', description: 'Access to Assigned Tasks tab' },
  { module: 'HRMS', action: 'Full Assigned Tasks Access', code: 'hrms.tasks.assigned.*', description: 'Complete access to Assigned Tasks actions' },
  { module: 'HRMS', action: 'Create Assigned Task', code: 'hrms.tasks.assigned.create', description: 'Ability to assign a new task' },
  { module: 'HRMS', action: 'Edit Assigned Task', code: 'hrms.tasks.assigned.edit', description: 'Ability to edit an assigned task' },
  { module: 'HRMS', action: 'Delete Assigned Task', code: 'hrms.tasks.assigned.delete', description: 'Ability to delete an assigned task' },
  { module: 'HRMS', action: 'Completed Tab Access', code: 'hrms.tasks.completed', description: 'Access to Completed Tasks tab' },
  { module: 'HRMS', action: 'Full Completed Tasks Access', code: 'hrms.tasks.completed.*', description: 'Complete access to Completed Tasks actions' },
  { module: 'HRMS', action: 'View Completed Task', code: 'hrms.tasks.completed.view', description: 'Ability to view completed tasks' },

  // 5. Report
  { module: 'HRMS', action: 'Report Layout Access', code: 'hrms.report', description: 'Access to Report sidebar/routes' },
  { module: 'HRMS', action: 'Full Report Access', code: 'hrms.report.*', description: 'Complete access to all Reports' },
  { module: 'HRMS', action: 'Attendance Report Tab Access', code: 'hrms.report.attendance', description: 'Access to Attendance Reports tab' },
  { module: 'HRMS', action: 'Full Attendance Report Access', code: 'hrms.report.attendance.*', description: 'Complete access to Attendance Reports' },
  { module: 'HRMS', action: 'Export Attendance Report', code: 'hrms.report.attendance.export', description: 'Ability to export attendance report' },
  { module: 'HRMS', action: 'Payroll Report Tab Access', code: 'hrms.report.payroll', description: 'Access to Payroll Reports tab' },
  { module: 'HRMS', action: 'Full Payroll Report Access', code: 'hrms.report.payroll.*', description: 'Complete access to Payroll Reports' },
  { module: 'HRMS', action: 'Export Payroll Report', code: 'hrms.report.payroll.export', description: 'Ability to export payroll report' },

  // 6. Payroll
  { module: 'HRMS', action: 'Payroll Layout Access', code: 'hrms.payroll', description: 'Access to Payroll sidebar/routes' },
  { module: 'HRMS', action: 'Full Payroll Access', code: 'hrms.payroll.*', description: 'Complete access to all Payroll features' },
  { module: 'HRMS', action: 'Salary Slips Tab Access', code: 'hrms.payroll.salary_slips', description: 'Access to Salary Slips tab' },
  { module: 'HRMS', action: 'Full Salary Slips Access', code: 'hrms.payroll.salary_slips.*', description: 'Complete access to Salary Slips actions' },
  { module: 'HRMS', action: 'Generate Salary Slip', code: 'hrms.payroll.salary_slips.generate', description: 'Ability to generate a salary slip' },
  { module: 'HRMS', action: 'Export Salary Slips', code: 'hrms.payroll.salary_slips.export', description: 'Ability to export salary slips' },
  { module: 'HRMS', action: 'Advances Tab Access', code: 'hrms.payroll.advances', description: 'Access to Salary Advances tab' },
  { module: 'HRMS', action: 'Full Advances Access', code: 'hrms.payroll.advances.*', description: 'Complete access to Salary Advances actions' },
  { module: 'HRMS', action: 'Approve Advance', code: 'hrms.payroll.advances.approve', description: 'Ability to approve a salary advance' },

  // 7. Job
  { module: 'HRMS', action: 'Job Layout Access', code: 'hrms.job', description: 'Access to Job sidebar/routes' },
  { module: 'HRMS', action: 'Full Job Access', code: 'hrms.job.*', description: 'Complete access to all Job features' },
  { module: 'HRMS', action: 'Active Jobs Tab Access', code: 'hrms.job.active_jobs', description: 'Access to Active Job Postings tab' },
  { module: 'HRMS', action: 'Full Active Jobs Access', code: 'hrms.job.active_jobs.*', description: 'Complete access to Active Jobs actions' },
  { module: 'HRMS', action: 'Create Job', code: 'hrms.job.active_jobs.create', description: 'Ability to post a new job' },
  { module: 'HRMS', action: 'Edit Job', code: 'hrms.job.active_jobs.edit', description: 'Ability to edit a job post' },
  { module: 'HRMS', action: 'Delete Job', code: 'hrms.job.active_jobs.delete', description: 'Ability to delete a job post' },
  { module: 'HRMS', action: 'Applications Tab Access', code: 'hrms.job.applications', description: 'Access to Job Applications tab' },
  { module: 'HRMS', action: 'Full Applications Access', code: 'hrms.job.applications.*', description: 'Complete access to Applications actions' },
  { module: 'HRMS', action: 'View Application', code: 'hrms.job.applications.view', description: 'Ability to view applicant details' },
  { module: 'HRMS', action: 'Shortlist Application', code: 'hrms.job.applications.shortlist', description: 'Ability to shortlist an applicant' },

  // 8. Message
  { module: 'HRMS', action: 'Message Layout Access', code: 'hrms.message', description: 'Access to Message sidebar/routes' },
  { module: 'HRMS', action: 'Full Message Access', code: 'hrms.message.*', description: 'Complete access to all Message features' },
  { module: 'HRMS', action: 'Inbox Tab Access', code: 'hrms.message.inbox', description: 'Access to Message Inbox tab' },
  { module: 'HRMS', action: 'Full Inbox Access', code: 'hrms.message.inbox.*', description: 'Complete access to Inbox actions' },
  { module: 'HRMS', action: 'Reply Message', code: 'hrms.message.inbox.reply', description: 'Ability to reply to a message' },
  { module: 'HRMS', action: 'Delete Message', code: 'hrms.message.inbox.delete', description: 'Ability to delete a message' },
  { module: 'HRMS', action: 'Sent Tab Access', code: 'hrms.message.sent', description: 'Access to Sent Messages tab' },
  { module: 'HRMS', action: 'Full Sent Access', code: 'hrms.message.sent.*', description: 'Complete access to Sent Messages actions' },
  { module: 'HRMS', action: 'Create Message', code: 'hrms.message.sent.create', description: 'Ability to compose/send a new message' },

  // 9. Calendar
  { module: 'HRMS', action: 'Calendar Layout Access', code: 'hrms.calendar', description: 'Access to Calendar sidebar/routes' },
  { module: 'HRMS', action: 'Full Calendar Access', code: 'hrms.calendar.*', description: 'Complete access to all Calendar features' },
  { module: 'HRMS', action: 'Events Tab Access', code: 'hrms.calendar.events', description: 'Access to Calendar Events tab' },
  { module: 'HRMS', action: 'Full Events Access', code: 'hrms.calendar.events.*', description: 'Complete access to Events actions' },
  { module: 'HRMS', action: 'Create Event', code: 'hrms.calendar.events.create', description: 'Ability to add a new event to calendar' },
  { module: 'HRMS', action: 'Edit Event', code: 'hrms.calendar.events.edit', description: 'Ability to edit a calendar event' },
  { module: 'HRMS', action: 'Delete Event', code: 'hrms.calendar.events.delete', description: 'Ability to delete a calendar event' },
  { module: 'HRMS', action: 'Holidays Tab Access', code: 'hrms.calendar.holidays', description: 'Access to Holidays list tab' },
  { module: 'HRMS', action: 'Full Holidays Access', code: 'hrms.calendar.holidays.*', description: 'Complete access to Holidays actions' },
  { module: 'HRMS', action: 'Create Holiday', code: 'hrms.calendar.holidays.create', description: 'Ability to declare a new holiday' },
];
